param(
  [Parameter(Mandatory=$true)]
  [string]$RepoRoot
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Die([string]$m){ throw $m }

function Ensure-Dir([string]$p){
  if([string]::IsNullOrWhiteSpace($p)){ Die "Ensure-Dir: empty path" }
  if(-not (Test-Path -LiteralPath $p -PathType Container)){
    New-Item -ItemType Directory -Force -Path $p | Out-Null
  }
}

function Write-Utf8NoBomLf([string]$path, [string]$text){
  $dir = Split-Path -Parent $path
  if(-not [string]::IsNullOrWhiteSpace($dir)){ Ensure-Dir $dir }
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  $bytes = $utf8NoBom.GetBytes($text.Replace("`r`n","`n"))
  [System.IO.File]::WriteAllBytes($path, $bytes)
}

function Write-Lines([string]$path, [string[]]$lines){
  Write-Utf8NoBomLf $path ((@($lines) -join "`n") + "`n")
}

$RepoRootAbs = (Resolve-Path -LiteralPath $RepoRoot).Path

# --- 0) Create required dirs ---
$dirs = @(
  "docs",
  "src",
  "src\CDE.Runtime\Engine",
  "src\CDE.Runtime\Engine\Scene",
  "src\CDE.Runtime\Engine\Graphics",
  "src\CDE.Runtime\Engine\Input",
  "src\CDE.Runtime\Engine\Debug",
  "src\CDE.Runtime\Engine\Platformer\Tilemap",
  "src\CDE.Runtime\Engine\Platformer\Physics",
  "src\CDE.Runtime\Engine\Platformer\Controller",
  "src\CDE.Game",
  "src\CDE.Tools.Forge",
  "src\CDE.Tools.Forge\Commands",
  "src\CDE.Tools.Forge\Pipeline",
  "src\CDE.Tools.Forge\Formats",
  "assets_src\levels",
  "tools\scripts"
)

foreach($d in $dirs){
  Ensure-Dir (Join-Path $RepoRootAbs $d)
}

# --- 1) v0.1 Runtime core files ---
Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\CdeGame.cs") @(
'using Microsoft.Xna.Framework;',
'using Microsoft.Xna.Framework.Graphics;',
'using Microsoft.Xna.Framework.Input;',
'',
'namespace CDE.Runtime.Engine;',
'',
'public abstract class CdeGame : Game',
'{',
'    private readonly GraphicsDeviceManager _gdm;',
'',
'    protected CdeGame()',
'    {',
'        _gdm = new GraphicsDeviceManager(this);',
'        IsMouseVisible = true;',
'        Content.RootDirectory = "Content";',
'    }',
'',
'    protected GraphicsDeviceManager GraphicsManager => _gdm;',
'',
'    protected override void Initialize()',
'    {',
'        base.Initialize();',
'        Window.AllowUserResizing = true;',
'    }',
'',
'    protected void ExitIfRequested()',
'    {',
'        var kb = Keyboard.GetState();',
'        if (kb.IsKeyDown(Keys.Escape)) Exit();',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Scene\Scene.cs") @(
'using Microsoft.Xna.Framework;',
'using Microsoft.Xna.Framework.Graphics;',
'',
'namespace CDE.Runtime.Engine.Scene;',
'',
'public abstract class Scene',
'{',
'    public virtual void OnEnter() { }',
'    public virtual void OnExit() { }',
'',
'    // FixedUpdate runs at a fixed timestep (e.g. 60Hz) for physics & controllers.',
'    public virtual void FixedUpdate(GameTime gameTime) { }',
'',
'    // Update runs every frame (input sampling, timers).',
'    public virtual void Update(GameTime gameTime) { }',
'',
'    public virtual void Draw(GameTime gameTime, SpriteBatch spriteBatch) { }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Scene\SceneStack.cs") @(
'using System.Collections.Generic;',
'',
'namespace CDE.Runtime.Engine.Scene;',
'',
'public sealed class SceneStack',
'{',
'    private readonly Stack<Scene> _stack = new();',
'',
'    public Scene? Current => _stack.Count > 0 ? _stack.Peek() : null;',
'',
'    public void Push(Scene scene)',
'    {',
'        _stack.Push(scene);',
'        scene.OnEnter();',
'    }',
'',
'    public void Pop()',
'    {',
'        if (_stack.Count <= 0) return;',
'        var s = _stack.Pop();',
'        s.OnExit();',
'    }',
'',
'    public void Clear()',
'    {',
'        while (_stack.Count > 0) Pop();',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Graphics\PixelPerfectRenderer.cs") @(
'using Microsoft.Xna.Framework;',
'using Microsoft.Xna.Framework.Graphics;',
'',
'namespace CDE.Runtime.Engine.Graphics;',
'',
'/// <summary>',
'/// PixelPerfectRenderer:',
'/// - Draw world into a fixed virtual RenderTarget2D',
'/// - Upscale to backbuffer using integer scale only',
'/// - Letterbox remaining space',
'/// - Point sampling only',
'/// </summary>',
'public sealed class PixelPerfectRenderer : System.IDisposable',
'{',
'    private readonly GraphicsDevice _gd;',
'    private RenderTarget2D? _rt;',
'',
'    public int VirtualWidth { get; private set; }',
'    public int VirtualHeight { get; private set; }',
'',
'    public int IntegerScale { get; private set; } = 1;',
'    public Rectangle DestinationRect { get; private set; }',
'',
'    public PixelPerfectRenderer(GraphicsDevice gd, int virtualWidth, int virtualHeight)',
'    {',
'        _gd = gd;',
'        SetVirtualResolution(virtualWidth, virtualHeight);',
'    }',
'',
'    public void SetVirtualResolution(int w, int h)',
'    {',
'        if (w <= 0 || h <= 0) throw new System.ArgumentOutOfRangeException(nameof(w));',
'        VirtualWidth = w;',
'        VirtualHeight = h;',
'',
'        _rt?.Dispose();',
'        _rt = new RenderTarget2D(',
'            _gd,',
'            VirtualWidth,',
'            VirtualHeight,',
'            false,',
'            SurfaceFormat.Color,',
'            DepthFormat.None,',
'            0,',
'            RenderTargetUsage.DiscardContents',
'        );',
'',
'        RecalculateDestination(_gd.PresentationParameters.BackBufferWidth, _gd.PresentationParameters.BackBufferHeight);',
'    }',
'',
'    public void OnBackBufferResized(int backBufferW, int backBufferH)',
'        => RecalculateDestination(backBufferW, backBufferH);',
'',
'    private void RecalculateDestination(int backBufferW, int backBufferH)',
'    {',
'        if (backBufferW <= 0 || backBufferH <= 0) return;',
'',
'        var sx = backBufferW / VirtualWidth;',
'        var sy = backBufferH / VirtualHeight;',
'        var scale = System.Math.Max(1, System.Math.Min(sx, sy));',
'        IntegerScale = scale;',
'',
'        var dstW = VirtualWidth * scale;',
'        var dstH = VirtualHeight * scale;',
'        var x = (backBufferW - dstW) / 2;',
'        var y = (backBufferH - dstH) / 2;',
'        DestinationRect = new Rectangle(x, y, dstW, dstH);',
'    }',
'',
'    public void BeginVirtual()',
'    {',
'        if (_rt == null) throw new System.InvalidOperationException("RenderTarget not initialized.");',
'        _gd.SetRenderTarget(_rt);',
'        _gd.Clear(Color.Transparent);',
'    }',
'',
'    public void EndVirtualAndBlitToBackbuffer(SpriteBatch sb, Color clearColor)',
'    {',
'        if (_rt == null) throw new System.InvalidOperationException("RenderTarget not initialized.");',
'',
'        _gd.SetRenderTarget(null);',
'        _gd.Clear(clearColor);',
'',
'        sb.Begin(',
'            SpriteSortMode.Deferred,',
'            BlendState.AlphaBlend,',
'            SamplerState.PointClamp,',
'            DepthStencilState.None,',
'            RasterizerState.CullNone',
'        );',
'',
'        sb.Draw(_rt, DestinationRect, Color.White);',
'        sb.End();',
'    }',
'',
'    public void Dispose()',
'    {',
'        _rt?.Dispose();',
'        _rt = null;',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Graphics\PixelPerfectCamera2D.cs") @(
'using Microsoft.Xna.Framework;',
'',
'namespace CDE.Runtime.Engine.Graphics;',
'',
'/// <summary>',
'/// Camera that snaps its translation to integer pixels in virtual space.',
'/// World units are pixels by default (1 unit = 1 pixel).',
'/// </summary>',
'public sealed class PixelPerfectCamera2D',
'{',
'    public Vector2 Position { get; set; } = Vector2.Zero;',
'    public Vector2 Origin { get; set; } = Vector2.Zero;',
'',
'    /// <summary>Optional smoothing (0 = none). Keep small (e.g., 0.10f).</summary>',
'    public float SmoothFollow { get; set; } = 0f;',
'',
'    public void Follow(Vector2 target)',
'    {',
'        if (SmoothFollow <= 0f)',
'        {',
'            Position = target;',
'            return;',
'        }',
'        Position = Vector2.Lerp(Position, target, SmoothFollow);',
'    }',
'',
'    public Matrix GetViewMatrix()',
'    {',
'        var snapped = new Vector2((float)System.Math.Floor(Position.X), (float)System.Math.Floor(Position.Y));',
'        return Matrix.CreateTranslation(new Vector3(-snapped + Origin, 0f));',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Graphics\SpriteDraw.cs") @(
'using Microsoft.Xna.Framework;',
'using Microsoft.Xna.Framework.Graphics;',
'',
'namespace CDE.Runtime.Engine.Graphics;',
'',
'public static class SpriteDraw',
'{',
'    public static Vector2 Snap(Vector2 p)',
'        => new((float)System.Math.Round(p.X), (float)System.Math.Round(p.Y));',
'',
'    public static void DrawSnapped(',
'        SpriteBatch sb,',
'        Texture2D tex,',
'        Vector2 pos,',
'        Rectangle? src,',
'        Color color)',
'    {',
'        sb.Draw(tex, Snap(pos), src, color);',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Input\InputAction.cs") @(
'namespace CDE.Runtime.Engine.Input;',
'',
'public enum InputAction',
'{',
'    MoveLeft,',
'    MoveRight,',
'    Jump,',
'    Pause',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Input\InputState.cs") @(
'namespace CDE.Runtime.Engine.Input;',
'',
'public readonly struct InputState',
'{',
'    public readonly bool Down;',
'    public readonly bool Pressed;',
'    public readonly bool Released;',
'',
'    public InputState(bool down, bool pressed, bool released)',
'    {',
'        Down = down;',
'        Pressed = pressed;',
'        Released = released;',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Input\InputMap.cs") @(
'using System.Collections.Generic;',
'using Microsoft.Xna.Framework.Input;',
'',
'namespace CDE.Runtime.Engine.Input;',
'',
'/// <summary>',
'/// Action-based input mapping. Keyboard-only v0.1 (gamepad later).',
'/// </summary>',
'public sealed class InputMap',
'{',
'    private readonly Dictionary<InputAction, Keys[]> _map = new();',
'    private KeyboardState _prev;',
'    private KeyboardState _cur;',
'',
'    public void Set(InputAction action, params Keys[] keys)',
'        => _map[action] = keys ?? System.Array.Empty<Keys>();',
'',
'    public void Update()',
'    {',
'        _prev = _cur;',
'        _cur = Keyboard.GetState();',
'    }',
'',
'    public InputState Get(InputAction action)',
'    {',
'        if (!_map.TryGetValue(action, out var keys) || keys.Length == 0)',
'            return new InputState(false, false, false);',
'',
'        bool curDown = false;',
'        bool prevDown = false;',
'',
'        for (var i = 0; i < keys.Length; i++)',
'        {',
'            var k = keys[i];',
'            curDown |= _cur.IsKeyDown(k);',
'            prevDown |= _prev.IsKeyDown(k);',
'        }',
'',
'        var pressed = curDown && !prevDown;',
'        var released = !curDown && prevDown;',
'        return new InputState(curDown, pressed, released);',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Debug\DebugOverlay.cs") @(
'using Microsoft.Xna.Framework;',
'using Microsoft.Xna.Framework.Graphics;',
'',
'namespace CDE.Runtime.Engine.Debug;',
'',
'public sealed class DebugOverlay',
'{',
'    private double _accum;',
'    private int _frames;',
'    private int _fps;',
'',
'    public bool Enabled { get; set; } = true;',
'',
'    public void Update(GameTime gt)',
'    {',
'        _accum += gt.ElapsedGameTime.TotalSeconds;',
'        _frames++;',
'',
'        if (_accum >= 1.0)',
'        {',
'            _fps = _frames;',
'            _frames = 0;',
'            _accum = 0;',
'        }',
'    }',
'',
'    public void Draw(SpriteBatch sb, SpriteFont font)',
'    {',
'        if (!Enabled) return;',
'        sb.DrawString(font, $"FPS: {_fps}", new Vector2(4, 4), Color.White);',
'    }',
'}'
)

# --- 2) v0.2 Platformer core ---
Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Platformer\Physics\Aabb.cs") @(
'using Microsoft.Xna.Framework;',
'',
'namespace CDE.Runtime.Engine.Platformer.Physics;',
'',
'public readonly struct Aabb',
'{',
'    public readonly float X;',
'    public readonly float Y;',
'    public readonly float W;',
'    public readonly float H;',
'',
'    public Aabb(float x, float y, float w, float h)',
'    {',
'        X = x; Y = y; W = w; H = h;',
'    }',
'',
'    public float Left => X;',
'    public float Right => X + W;',
'    public float Top => Y;',
'    public float Bottom => Y + H;',
'',
'    public Aabb WithXY(float x, float y) => new Aabb(x, y, W, H);',
'    public Rectangle ToRect() => new Rectangle((int)System.Math.Floor(X), (int)System.Math.Floor(Y), (int)System.Math.Ceiling(W), (int)System.Math.Ceiling(H));',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Platformer\Tilemap\Tilemap.cs") @(
'namespace CDE.Runtime.Engine.Platformer.Tilemap;',
'',
'public sealed class Tilemap',
'{',
'    public int TileSize { get; }',
'    public int Width { get; }',
'    public int Height { get; }',
'    private readonly bool[] _solid;',
'',
'    public Tilemap(int tileSize, int width, int height)',
'    {',
'        if (tileSize <= 0) throw new System.ArgumentOutOfRangeException(nameof(tileSize));',
'        if (width <= 0 || height <= 0) throw new System.ArgumentOutOfRangeException(nameof(width));',
'        TileSize = tileSize;',
'        Width = width;',
'        Height = height;',
'        _solid = new bool[width * height];',
'    }',
'',
'    public bool InBounds(int tx, int ty) => tx >= 0 && ty >= 0 && tx < Width && ty < Height;',
'    public bool IsSolid(int tx, int ty) => InBounds(tx, ty) && _solid[(ty * Width) + tx];',
'',
'    public void SetSolid(int tx, int ty, bool solid)',
'    {',
'        if (!InBounds(tx, ty)) return;',
'        _solid[(ty * Width) + tx] = solid;',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Platformer\Tilemap\TileCollision.cs") @(
'using CDE.Runtime.Engine.Platformer.Physics;',
'',
'namespace CDE.Runtime.Engine.Platformer.Tilemap;',
'',
'public static class TileCollision',
'{',
'    // Resolve X then Y (platformer-friendly).',
'    public static void ResolveSolidTiles(Tilemap map, ref float x, ref float y, float w, float h, ref float vx, ref float vy, out bool grounded)',
'    {',
'        grounded = false;',
'',
'        // --- X move ---',
'        if (vx != 0f)',
'        {',
'            var newX = x + vx;',
'            var box = new Aabb(newX, y, w, h);',
'            if (Collides(map, box))',
'            {',
'                // step back to nearest non-colliding pixel',
'                var step = vx > 0f ? 1f : -1f;',
'                while (!Collides(map, new Aabb(x + step, y, w, h)))',
'                {',
'                    x += step;',
'                }',
'                vx = 0f;',
'            }',
'            else',
'            {',
'                x = newX;',
'            }',
'        }',
'',
'        // --- Y move ---',
'        if (vy != 0f)',
'        {',
'            var newY = y + vy;',
'            var box = new Aabb(x, newY, w, h);',
'            if (Collides(map, box))',
'            {',
'                var step = vy > 0f ? 1f : -1f;',
'                while (!Collides(map, new Aabb(x, y + step, w, h)))',
'                {',
'                    y += step;',
'                }',
'',
'                // if we were moving down and hit something, we are grounded',
'                if (vy > 0f) grounded = true;',
'                vy = 0f;',
'            }',
'            else',
'            {',
'                y = newY;',
'            }',
'        }',
'    }',
'',
'    private static bool Collides(Tilemap map, Aabb box)',
'    {',
'        var ts = map.TileSize;',
'        int left = (int)System.Math.Floor(box.Left / ts);',
'        int right = (int)System.Math.Floor((box.Right - 0.001f) / ts);',
'        int top = (int)System.Math.Floor(box.Top / ts);',
'        int bottom = (int)System.Math.Floor((box.Bottom - 0.001f) / ts);',
'',
'        for (int ty = top; ty <= bottom; ty++)',
'        for (int tx = left; tx <= right; tx++)',
'        {',
'            if (map.IsSolid(tx, ty)) return true;',
'        }',
'        return false;',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Platformer\Controller\PlatformerTuning.cs") @(
'namespace CDE.Runtime.Engine.Platformer.Controller;',
'',
'public sealed class PlatformerTuning',
'{',
'    // Units are pixels and ticks are 60Hz fixed steps.',
'    public float MoveSpeedPxPerSec { get; set; } = 90f;',
'    public float JumpSpeedPxPerSec { get; set; } = 230f;',
'    public float GravityPxPerSec2 { get; set; } = 650f;',
'    public float MaxFallSpeedPxPerSec { get; set; } = 420f;',
'',
'    // Feel features',
'    public int CoyoteTicks { get; set; } = 6;       // ~100ms at 60Hz',
'    public int JumpBufferTicks { get; set; } = 6;   // ~100ms at 60Hz',
'',
'    // Variable jump: if player releases jump early, cut upward velocity',
'    public float JumpCutMultiplier { get; set; } = 0.45f;',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Runtime\Engine\Platformer\Controller\PlatformerController.cs") @(
'using CDE.Runtime.Engine.Input;',
'using CDE.Runtime.Engine.Platformer.Tilemap;',
'',
'namespace CDE.Runtime.Engine.Platformer.Controller;',
'',
'public sealed class PlatformerController',
'{',
'    private readonly PlatformerTuning _t;',
'    private int _coyote;',
'    private int _jumpBuf;',
'    public bool Grounded { get; private set; }',
'',
'    public float X;',
'    public float Y;',
'    public float Vx;',
'    public float Vy;',
'',
'    public float W = 10f;',
'    public float H = 14f;',
'',
'    public PlatformerController(PlatformerTuning tuning, float startX, float startY)',
'    {',
'        _t = tuning;',
'        X = startX;',
'        Y = startY;',
'    }',
'',
'    public void FixedTick60(InputMap input, Tilemap map)',
'    {',
'        // Update timers',
'        if (Grounded) _coyote = _t.CoyoteTicks; else if (_coyote > 0) _coyote--;',
'        if (_jumpBuf > 0) _jumpBuf--;',
'',
'        // Horizontal',
'        var left = input.Get(InputAction.MoveLeft).Down;',
'        var right = input.Get(InputAction.MoveRight).Down;',
'        var move = (left ? -1 : 0) + (right ? 1 : 0);',
'',
'        var movePerTick = _t.MoveSpeedPxPerSec / 60f;',
'        Vx = move * movePerTick;',
'',
'        // Jump buffer',
'        var jumpPressed = input.Get(InputAction.Jump).Pressed;',
'        var jumpDown = input.Get(InputAction.Jump).Down;',
'        var jumpReleased = input.Get(InputAction.Jump).Released;',
'',
'        if (jumpPressed) _jumpBuf = _t.JumpBufferTicks;',
'',
'        // Jump if buffered and we are within coyote/grounded',
'        if (_jumpBuf > 0 && (_coyote > 0 || Grounded))',
'        {',
'            Vy = -(_t.JumpSpeedPxPerSec / 60f);',
'            Grounded = false;',
'            _coyote = 0;',
'            _jumpBuf = 0;',
'        }',
'',
'        // Variable jump cut',
'        if (jumpReleased && Vy < 0f)',
'        {',
'            Vy *= _t.JumpCutMultiplier;',
'        }',
'',
'        // Gravity',
'        Vy += (_t.GravityPxPerSec2 / 60f) / 60f; // (px/s^2) -> per-tick delta',
'',
'        var maxFallPerTick = _t.MaxFallSpeedPxPerSec / 60f;',
'        if (Vy > maxFallPerTick) Vy = maxFallPerTick;',
'',
'        // Resolve collisions (vx/vy are in pixels per tick)',
'        var vx = Vx;',
'        var vy = Vy;',
'        TileCollision.ResolveSolidTiles(map, ref X, ref Y, W, H, ref vx, ref vy, out var groundedNow);',
'        Vx = vx;',
'        Vy = vy;',
'        Grounded = groundedNow;',
'',
'        // If grounded, kill tiny downward drift',
'        if (Grounded && Vy > 0f) Vy = 0f;',
'    }',
'}'
)

# --- 3) v0.1 Forge skeleton (minimal) ---
Write-Lines (Join-Path $RepoRootAbs "src\CDE.Tools.Forge\Program.cs") @(
'using CDE.Tools.Forge;',
'',
'return await ForgeProgram.MainAsync(args);'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Tools.Forge\ForgeProgram.cs") @(
'using System;',
'using System.IO;',
'using System.Threading.Tasks;',
'using CDE.Tools.Forge.Commands;',
'',
'namespace CDE.Tools.Forge;',
'',
'public static class ForgeProgram',
'{',
'    public static async Task<int> MainAsync(string[] args)',
'    {',
'        var cmd = args.Length > 0 ? args[0].Trim().ToLowerInvariant() : "help";',
'        var repoRoot = FindRepoRoot(Directory.GetCurrentDirectory());',
'        if (repoRoot == null)',
'        {',
'            Console.Error.WriteLine("FORGE_ERR: could not find repo root (expected CDE.sln)");',
'            return 2;',
'        }',
'',
'        var ctx = new ForgeContext(repoRoot);',
'',
'        try',
'        {',
'            return cmd switch',
'            {',
'                "build"  => await new BuildCommand().Run(ctx),',
'                "run"    => await new RunCommand().Run(ctx),',
'                "import" => await new ImportCommand().Run(ctx, args),',
'                "clean"  => await new CleanCommand().Run(ctx),',
'                "doctor" => await new DoctorCommand().Run(ctx),',
'                _        => Help()',
'            };',
'        }',
'        catch (Exception ex)',
'        {',
'            Console.Error.WriteLine("FORGE_FAIL: " + ex.Message);',
'            return 1;',
'        }',
'    }',
'',
'    private static int Help()',
'    {',
'        Console.WriteLine("CDE Forge v0.1");',
'        Console.WriteLine("Usage:");',
'        Console.WriteLine("  forge build");',
'        Console.WriteLine("  forge run");',
'        Console.WriteLine("  forge import <path>");',
'        Console.WriteLine("  forge clean");',
'        Console.WriteLine("  forge doctor");',
'        return 0;',
'    }',
'',
'    private static string? FindRepoRoot(string start)',
'    {',
'        var cur = new DirectoryInfo(start);',
'        while (cur != null)',
'        {',
'            var sln = Path.Combine(cur.FullName, "CDE.sln");',
'            if (File.Exists(sln)) return cur.FullName;',
'            cur = cur.Parent;',
'        }',
'        return null;',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Tools.Forge\ForgeContext.cs") @(
'using System.IO;',
'',
'namespace CDE.Tools.Forge;',
'',
'public sealed class ForgeContext',
'{',
'    public string RepoRoot { get; }',
'    public string AssetsSrc { get; }',
'    public string AssetsBuild { get; }',
'',
'    public ForgeContext(string repoRoot)',
'    {',
'        RepoRoot = repoRoot;',
'        AssetsSrc = Path.Combine(repoRoot, "assets_src");',
'        AssetsBuild = Path.Combine(repoRoot, "assets_build");',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Tools.Forge\Pipeline\AssetScanner.cs") @(
'using System.Collections.Generic;',
'using System.IO;',
'',
'namespace CDE.Tools.Forge.Pipeline;',
'',
'public static class AssetScanner',
'{',
'    public static IEnumerable<string> ScanAllFiles(string root)',
'    {',
'        if (!Directory.Exists(root)) yield break;',
'',
'        foreach (var f in Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories))',
'        {',
'            var name = Path.GetFileName(f).ToLowerInvariant();',
'            if (name == "thumbs.db") continue;',
'            if (name.EndsWith(".tmp")) continue;',
'            yield return f;',
'        }',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Tools.Forge\Commands\BuildCommand.cs") @(
'using System;',
'using System.IO;',
'using System.Linq;',
'using System.Text.Json;',
'using System.Threading.Tasks;',
'using CDE.Tools.Forge.Pipeline;',
'',
'namespace CDE.Tools.Forge.Commands;',
'',
'public sealed class BuildCommand',
'{',
'    public Task<int> Run(ForgeContext ctx)',
'    {',
'        Directory.CreateDirectory(ctx.AssetsSrc);',
'        Directory.CreateDirectory(ctx.AssetsBuild);',
'',
'        var files = AssetScanner.ScanAllFiles(ctx.AssetsSrc)',
'            .OrderBy(p => p.Replace(''\\'',''/'') , StringComparer.Ordinal)',
'            .ToArray();',
'',
'        foreach (var src in files)',
'        {',
'            var rel = Path.GetRelativePath(ctx.AssetsSrc, src);',
'            var dst = Path.Combine(ctx.AssetsBuild, rel);',
'            Directory.CreateDirectory(Path.GetDirectoryName(dst)!);',
'            File.Copy(src, dst, overwrite: true);',
'        }',
'',
'        var manifest = new',
'        {',
'            schema = "cde.assets.manifest.v1",',
'            generated_utc = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ"),',
'            files = files.Select(f => Path.GetRelativePath(ctx.AssetsSrc, f).Replace(''\\'',''/'')).ToArray()',
'        };',
'',
'        var json = JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true });',
'        File.WriteAllText(Path.Combine(ctx.AssetsBuild, "manifest.json"), json);',
'',
'        Console.WriteLine($"FORGE_BUILD_OK: files={files.Length}");',
'        return Task.FromResult(0);',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Tools.Forge\Commands\RunCommand.cs") @(
'using System;',
'using System.Diagnostics;',
'using System.IO;',
'using System.Threading.Tasks;',
'',
'namespace CDE.Tools.Forge.Commands;',
'',
'public sealed class RunCommand',
'{',
'    public async Task<int> Run(ForgeContext ctx)',
'    {',
'        var b = await new BuildCommand().Run(ctx);',
'        if (b != 0) return b;',
'',
'        var gameProj = Path.Combine(ctx.RepoRoot, "src", "CDE.Game", "CDE.Game.csproj");',
'        if (!File.Exists(gameProj))',
'        {',
'            Console.Error.WriteLine("FORGE_ERR: missing CDE.Game.csproj at src/CDE.Game/");',
'            return 2;',
'        }',
'',
'        var psi = new ProcessStartInfo',
'        {',
'            FileName = "dotnet",',
'            Arguments = $"run --project \\"{gameProj}\\"",',
'            UseShellExecute = false',
'        };',
'',
'        Console.WriteLine("FORGE_RUN: dotnet " + psi.Arguments);',
'        using var p = Process.Start(psi);',
'        if (p == null) return 3;',
'        await p.WaitForExitAsync();',
'        return p.ExitCode;',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Tools.Forge\Commands\CleanCommand.cs") @(
'using System;',
'using System.IO;',
'using System.Threading.Tasks;',
'',
'namespace CDE.Tools.Forge.Commands;',
'',
'public sealed class CleanCommand',
'{',
'    public Task<int> Run(ForgeContext ctx)',
'    {',
'        if (Directory.Exists(ctx.AssetsBuild))',
'        {',
'            Directory.Delete(ctx.AssetsBuild, recursive: true);',
'            Console.WriteLine("FORGE_CLEAN_OK: assets_build deleted");',
'        }',
'        else',
'        {',
'            Console.WriteLine("FORGE_CLEAN_OK: nothing to clean");',
'        }',
'        return Task.FromResult(0);',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Tools.Forge\Commands\DoctorCommand.cs") @(
'using System;',
'using System.IO;',
'using System.Threading.Tasks;',
'',
'namespace CDE.Tools.Forge.Commands;',
'',
'public sealed class DoctorCommand',
'{',
'    public Task<int> Run(ForgeContext ctx)',
'    {',
'        Console.WriteLine("FORGE_DOCTOR:");',
'        Console.WriteLine("  repo_root=" + ctx.RepoRoot);',
'        Console.WriteLine("  assets_src_exists=" + Directory.Exists(ctx.AssetsSrc));',
'        Console.WriteLine("  assets_build_exists=" + Directory.Exists(ctx.AssetsBuild));',
'        Console.WriteLine("FORGE_DOCTOR_OK");',
'        return Task.FromResult(0);',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Tools.Forge\Commands\ImportCommand.cs") @(
'using System;',
'using System.IO;',
'using System.Threading.Tasks;',
'',
'namespace CDE.Tools.Forge.Commands;',
'',
'public sealed class ImportCommand',
'{',
'    public Task<int> Run(ForgeContext ctx, string[] args)',
'    {',
'        if (args.Length < 2)',
'        {',
'            Console.Error.WriteLine("FORGE_IMPORT_ERR: missing <path>");',
'            return Task.FromResult(2);',
'        }',
'',
'        var srcPath = Path.GetFullPath(args[1]);',
'        if (!Directory.Exists(srcPath))',
'        {',
'            Console.Error.WriteLine("FORGE_IMPORT_ERR: directory not found: " + srcPath);',
'            return Task.FromResult(2);',
'        }',
'',
'        Directory.CreateDirectory(ctx.AssetsSrc);',
'',
'        var name = new DirectoryInfo(srcPath).Name;',
'        var dstRoot = Path.Combine(ctx.AssetsSrc, "imported", name);',
'        Directory.CreateDirectory(dstRoot);',
'',
'        foreach (var f in Directory.GetFiles(srcPath, "*", SearchOption.AllDirectories))',
'        {',
'            var rel = Path.GetRelativePath(srcPath, f);',
'            var dst = Path.Combine(dstRoot, rel);',
'            Directory.CreateDirectory(Path.GetDirectoryName(dst)!);',
'            File.Copy(f, dst, overwrite: true);',
'        }',
'',
'        Console.WriteLine("FORGE_IMPORT_OK: " + dstRoot);',
'        return Task.FromResult(0);',
'    }',
'}'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Tools.Forge\Formats\CdeSpriteProject.cs") @(
'namespace CDE.Tools.Forge.Formats;',
'',
'// v0.1 placeholder for .cdesprite.json',
'public sealed class CdeSpriteProject',
'{',
'    public string schema { get; set; } = "cde.sprite.project.v1";',
'    public int width { get; set; }',
'    public int height { get; set; }',
'    public object? palette { get; set; }',
'    public object[] layers { get; set; } = System.Array.Empty<object>();',
'    public object[] frames { get; set; } = System.Array.Empty<object>();',
'    public object[] tags { get; set; } = System.Array.Empty<object>();',
'}'
)

# --- 4) Game host files (MonoGame project will compile these once you create csproj) ---
Write-Lines (Join-Path $RepoRootAbs "src\CDE.Game\Program.cs") @(
'using var game = new CDE.Game.GameRoot();',
'game.Run();'
)

Write-Lines (Join-Path $RepoRootAbs "src\CDE.Game\GameRoot.cs") @(
'using Microsoft.Xna.Framework;',
'using Microsoft.Xna.Framework.Graphics;',
'using Microsoft.Xna.Framework.Input;',
'using CDE.Runtime.Engine;',
'using CDE.Runtime.Engine.Graphics;',
'using CDE.Runtime.Engine.Input;',
'using CDE.Runtime.Engine.Debug;',
'using CDE.Runtime.Engine.Platformer.Tilemap;',
'using CDE.Runtime.Engine.Platformer.Controller;',
'',
'namespace CDE.Game;',
'',
'public sealed class GameRoot : CdeGame',
'{',
'    // CDE law: all must be supported; default 320x180',
'    private static readonly (int w, int h) DefaultVirtual = (320, 180);',
'',
'    private SpriteBatch? _sb;',
'    private PixelPerfectRenderer? _ppr;',
'    private PixelPerfectCamera2D? _cam;',
'    private InputMap? _input;',
'    private DebugOverlay? _dbg;',
'',
'    private Texture2D? _px;',
'    private SpriteFont? _font;',
'',
'    private Tilemap? _map;',
'    private Texture2D? _tileTex;',
'    private PlatformerController? _ctrl;',
'    private PlatformerTuning? _tun;',
'',
'    private const double FixedDt = 1.0 / 60.0;',
'    private double _accum;',
'',
'    public GameRoot()',
'    {',
'        IsFixedTimeStep = false;',
'        GraphicsManager.SynchronizeWithVerticalRetrace = true;',
'    }',
'',
'    protected override void LoadContent()',
'    {',
'        _sb = new SpriteBatch(GraphicsDevice);',
'        _ppr = new PixelPerfectRenderer(GraphicsDevice, DefaultVirtual.w, DefaultVirtual.h);',
'        _cam = new PixelPerfectCamera2D { Origin = new Vector2(DefaultVirtual.w / 2f, DefaultVirtual.h / 2f) };',
'',
'        _input = new InputMap();',
'        _input.Set(InputAction.MoveLeft, Keys.A, Keys.Left);',
'        _input.Set(InputAction.MoveRight, Keys.D, Keys.Right);',
'        _input.Set(InputAction.Jump, Keys.Space);',
'        _input.Set(InputAction.Pause, Keys.Escape);',
'',
'        _dbg = new DebugOverlay { Enabled = true };',
'',
'        // 1x1 pixel for debug draws',
'        _px = new Texture2D(GraphicsDevice, 1, 1);',
'        _px.SetData(new[] { Color.White });',
'',
'        // tiny tile texture (solid gray)',
'        _tileTex = new Texture2D(GraphicsDevice, 16, 16);',
'        var td = new Color[16 * 16];',
'        for (int i = 0; i < td.Length; i++) td[i] = new Color(90, 90, 90);',
'        _tileTex.SetData(td);',
'',
'        TryLoadFont();',
'        BuildTestLevel();',
'',
'        _tun = new PlatformerTuning();',
'        _ctrl = new PlatformerController(_tun, startX: 40, startY: 40);',
'    }',
'',
'    private void TryLoadFont()',
'    {',
'        try { _font = Content.Load<SpriteFont>("DefaultFont"); }',
'        catch { _font = null; }',
'    }',
'',
'    private void BuildTestLevel()',
'    {',
'        // v0.2: procedural test room; later load from JSON',
'        _map = new Tilemap(tileSize: 16, width: 40, height: 22);',
'',
'        // Floor',
'        for (int x = 0; x < _map.Width; x++) _map.SetSolid(x, _map.Height - 2, true);',
'',
'        // A couple platforms',
'        for (int x = 8; x < 16; x++) _map.SetSolid(x, 14, true);',
'        for (int x = 22; x < 30; x++) _map.SetSolid(x, 10, true);',
'',
'        // Left wall chunk',
'        for (int y = 6; y < _map.Height - 2; y++) _map.SetSolid(2, y, true);',
'    }',
'',
'    protected override void OnExiting(object sender, System.EventArgs args)',
'    {',
'        _ppr?.Dispose();',
'        base.OnExiting(sender, args);',
'    }',
'',
'    protected override void Update(GameTime gameTime)',
'    {',
'        ExitIfRequested();',
'        if (_input == null || _cam == null || _dbg == null || _ctrl == null || _map == null) return;',
'',
'        _input.Update();',
'        if (_input.Get(InputAction.Pause).Pressed) Exit();',
'',
'        _accum += gameTime.ElapsedGameTime.TotalSeconds;',
'        while (_accum >= FixedDt)',
'        {',
'            _ctrl.FixedTick60(_input, _map);',
'            _accum -= FixedDt;',
'        }',
'',
'        // camera follows player center',
'        _cam.Follow(new Vector2(_ctrl.X + (_ctrl.W / 2f), _ctrl.Y + (_ctrl.H / 2f)));',
'',
'        _dbg.Update(gameTime);',
'        base.Update(gameTime);',
'    }',
'',
'    protected override void Draw(GameTime gameTime)',
'    {',
'        if (_sb == null || _ppr == null || _cam == null || _px == null || _tileTex == null || _map == null || _ctrl == null) return;',
'',
'        var pp = GraphicsDevice.PresentationParameters;',
'        _ppr.OnBackBufferResized(pp.BackBufferWidth, pp.BackBufferHeight);',
'',
'        _ppr.BeginVirtual();',
'',
'        _sb.Begin(',
'            SpriteSortMode.Deferred,',
'            BlendState.AlphaBlend,',
'            SamplerState.PointClamp,',
'            DepthStencilState.None,',
'            RasterizerState.CullNone,',
'            effect: null,',
'            transformMatrix: _cam.GetViewMatrix()',
'        );',
'',
'        // Draw tiles',
'        for (int y = 0; y < _map.Height; y++)',
'        for (int x = 0; x < _map.Width; x++)',
'        {',
'            if (_map.IsSolid(x, y))',
'            {',
'                var pxX = x * _map.TileSize;',
'                var pxY = y * _map.TileSize;',
'                _sb.Draw(_tileTex, new Vector2(pxX, pxY), Color.White);',
'            }',
'        }',
'',
'        // Draw player (white rect)',
'        _sb.Draw(_px, new Rectangle((int)System.Math.Round(_ctrl.X), (int)System.Math.Round(_ctrl.Y), (int)_ctrl.W, (int)_ctrl.H), Color.White);',
'',
'        _sb.End();',
'',
'        if (_font != null && _dbg != null)',
'        {',
'            _sb.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullNone);',
'            _dbg.Draw(_sb, _font);',
'            _sb.End();',
'        }',
'',
'        _ppr.EndVirtualAndBlitToBackbuffer(_sb, clearColor: Color.Black);',
'',
'        base.Draw(gameTime);',
'    }',
'}'
)

# --- 5) assets_src sample ---
Write-Lines (Join-Path $RepoRootAbs "assets_src\README.txt") @(
'Put source assets here (SpriteStudio .cdesprite.json, raw PNG, WAV, .blend).',
'Forge builds assets_build/ from this folder.'
)

Write-Utf8NoBomLf (Join-Path $RepoRootAbs "assets_src\levels\test_level_01.json") @"
{
  "schema": "cde.level.v1",
  "tileSize": 16,
  "width": 40,
  "height": 22,
  "layers": [
    { "type": "tile", "name": "solid", "data": [] }
  ],
  "entities": [
    { "type": "player", "x": 40, "y": 40 }
  ]
}
"@

Write-Host "BOOTSTRAP_CDE_OK: wrote v0.1 core + v0.2 platformer core into $RepoRootAbs" -ForegroundColor Green