param([Parameter(Mandatory=$true)][string]$RepoRoot)
$ErrorActionPreference="Stop"
Set-StrictMode -Version Latest
function Die([string]$m){ throw $m }
function Ensure-Dir([string]$p){ if([string]::IsNullOrWhiteSpace($p)){ Die "Ensure-Dir: empty" }; if(-not (Test-Path -LiteralPath $p -PathType Container)){ New-Item -ItemType Directory -Force -Path $p | Out-Null } }
function Write-Utf8NoBomLf([string]$path,[string]$text){ $dir = Split-Path -Parent $path; if(-not [string]::IsNullOrWhiteSpace($dir)){ Ensure-Dir $dir }; $u = New-Object System.Text.UTF8Encoding($false); $bytes = $u.GetBytes($text.Replace("`r`n","`n")); [System.IO.File]::WriteAllBytes($path,$bytes) }
function ReadAllTextUtf8([string]$p){ return [System.IO.File]::ReadAllText($p,[System.Text.Encoding]::UTF8) }
function Backup-IfExists([string]$p){ if(Test-Path -LiteralPath $p -PathType Leaf){ $ts=[DateTime]::UtcNow.ToString("yyyyMMdd_HHmmssZ"); $bak=($p + ".bak_" + $ts); Copy-Item -LiteralPath $p -Destination $bak -Force; Write-Host ("BACKUP: " + $bak) -ForegroundColor Yellow } }

$RepoRootAbs = (Resolve-Path -LiteralPath $RepoRoot).Path
$Sln = Join-Path $RepoRootAbs "CDE.sln"
if(-not (Test-Path -LiteralPath $Sln -PathType Leaf)){ Die ("MISSING_SOLUTION: " + $Sln) }

$EngineDir = Join-Path $RepoRootAbs "src\CDE.Runtime\Engine"
Ensure-Dir $EngineDir
$HostPath   = Join-Path $EngineDir "CdeGame.cs"
if(-not (Test-Path -LiteralPath $HostPath -PathType Leaf)){ Die ("MISSING_HOST: " + $HostPath) }
$BridgePath  = Join-Path $EngineDir "GameplayBridge.cs"
$OverlayPath = Join-Path $EngineDir "KernelOverlayComponent.cs"

Backup-IfExists $BridgePath
$bridgeLines = @(
  'using System;',
  'using System.IO;',
  'using System.Text;',
  'using CDE.Gameplay.Kernel;',
  '',
  'namespace CDE.Runtime.Engine;',
  '',
  'internal sealed class GameplayBridge',
  '{',
  '    public enum Mode { Yume, Mario }',
  '    public Mode ActiveMode { get; private set; } = Mode.Yume;',
  '',
  '    public string SceneId { get; private set; } = "StartRoom";',
  '    public float X { get; private set; } = 1f;',
  '    public float Y { get; private set; } = 1f;',
  '',
  '    public int MaxHp { get; private set; } = 5;',
  '    public int Hp { get; private set; } = 5;',
  '',
  '    public readonly FlagStore Flags = new();',
  '    private WarpKernel? _warp;',
  '    private KernelWorld? _mario;',
  '    public string Last { get; private set; } = "";',
  '',
  '    public void ResetToDefaults()',
  '    {',
  '        Flags.Clear();',
  '        Hp = MaxHp;',
  '        SetMode(Mode.Yume);',
  '    }',
  '',
  '    public void ApplyDamage(int amount)',
  '    {',
  '        if (amount <= 0) return;',
  '        Hp = Math.Max(0, Hp - amount);',
  '    }',
  '',
  '    public void Heal(int amount)',
  '    {',
  '        if (amount <= 0) return;',
  '        Hp = Math.Min(MaxHp, Hp + amount);',
  '    }',
  '',
  '    public void SetMode(Mode m)',
  '    {',
  '        ActiveMode = m;',
  '        if (m == Mode.Yume) { SceneId = "StartRoom"; X = 1f; Y = 1f; }',
  '        else { SceneId = "MarioRoom"; X = 0f; Y = 0f; }',
  '        Last = "";',
  '    }',
  '',
  '    public void LoadFromRepoRoot(string repoRoot)',
  '    {',
  '        var yumePath = Path.Combine(repoRoot, "assets_src", "gameplay", "warp_graph.v1.json");',
  '        var marioPath = Path.Combine(repoRoot, "assets_src", "gameplay", "mario_graph.v1.json");',
  '',
  '        if (File.Exists(yumePath))',
  '        {',
  '            var json = File.ReadAllText(yumePath, new UTF8Encoding(false));',
  '            var g = WarpKernel.LoadWarpGraphJson(json);',
  '            _warp = new WarpKernel(g, Flags);',
  '        }',
  '',
  '        if (File.Exists(marioPath))',
  '        {',
  '            var json = File.ReadAllText(marioPath, new UTF8Encoding(false));',
  '            _mario = KernelWorld.LoadMarioJson(json);',
  '        }',
  '    }',
  '',
  '    public int GetCoins() => _mario?.Inventory.GetCount("coin") ?? 0;',
  '    public int GetCoinTarget() => _mario?.Objectives.CoinTarget ?? 0;',
  '',
  '    public void Move(float dx, float dy){ X += dx; Y += dy; }',
  '',
  '    public void Tick()',
  '    {',
  '        if (ActiveMode == Mode.Yume)',
  '        {',
  '            if (_warp == null) { Last = ""; return; }',
  '            var r = _warp.TryWarp(new WarpKernel.WarpRequest(SceneId, X, Y));',
  '            if (r.Warped)',
  '            {',
  '                SceneId = r.NewSceneId; X = r.SpawnX; Y = r.SpawnY;',
  '                Last = r.MatchedWarpId;',
  '                return;',
  '            }',
  '            Last = "";',
  '        }',
  '        else',
  '        {',
  '            if (_mario == null) { Last = ""; return; }',
  '            var p = new KernelWorld.PlayerState(SceneId, X, Y);',
  '            var r = _mario.Tick(p);',
  '            SceneId = r.Player.SceneId; X = r.Player.X; Y = r.Player.Y;',
  '            Last = r.MatchedTriggerId ?? "";',
  '            if (!string.IsNullOrWhiteSpace(Last) && Last.IndexOf("damage", StringComparison.OrdinalIgnoreCase) >= 0)',
  '            {',
  '                ApplyDamage(1);',
  '            }',
  '        }',
  '    }',
  '}',
)
$bridgeText = (@($bridgeLines) -join "`n") + "`n"
Write-Utf8NoBomLf $BridgePath $bridgeText
Write-Host ("WROTE: " + $BridgePath) -ForegroundColor Green

Backup-IfExists $OverlayPath
$overlayLines = @(
  'using Microsoft.Xna.Framework;',
  'using Microsoft.Xna.Framework.Graphics;',
  'using Microsoft.Xna.Framework.Input;',
  'using XnaGame = Microsoft.Xna.Framework.Game;',
  '',
  'namespace CDE.Runtime.Engine;',
  '',
  'internal sealed class KernelOverlayComponent : DrawableGameComponent',
  '{',
  '    private readonly GameplayBridge _bridge;',
  '    private SpriteBatch? _sb;',
  '    private Texture2D? _px;',
  '    private KeyboardState _prev;',
  '    private bool _menu;',
  '',
  '    public KernelOverlayComponent(XnaGame game, GameplayBridge bridge) : base(game)',
  '    {',
  '        _bridge = bridge;',
  '        Enabled = true;',
  '        Visible = true;',
  '        UpdateOrder = int.MaxValue;',
  '        DrawOrder = int.MaxValue;',
  '    }',
  '',
  '    protected override void LoadContent()',
  '    {',
  '        _sb = new SpriteBatch(GraphicsDevice);',
  '        _px = new Texture2D(GraphicsDevice, 1, 1);',
  '        _px.SetData(new[] { Color.White });',
  '        base.LoadContent();',
  '    }',
  '',
  '    private static bool Pressed(Keys k, KeyboardState now, KeyboardState prev) => now.IsKeyDown(k) && !prev.IsKeyDown(k);',
  '',
  '    public override void Update(GameTime gameTime)',
  '    {',
  '        var k = Keyboard.GetState();',
  '        float s = 0.10f;',
  '',
  '        if (k.IsKeyDown(Keys.Left)  || k.IsKeyDown(Keys.A)) _bridge.Move(-s, 0);',
  '        if (k.IsKeyDown(Keys.Right) || k.IsKeyDown(Keys.D)) _bridge.Move( s, 0);',
  '        if (k.IsKeyDown(Keys.Up)    || k.IsKeyDown(Keys.W)) _bridge.Move(0, -s);',
  '        if (k.IsKeyDown(Keys.Down)  || k.IsKeyDown(Keys.S)) _bridge.Move(0,  s);',
  '',
  '        if (Pressed(Keys.F1, k, _prev)) _bridge.SetMode(GameplayBridge.Mode.Yume);',
  '        if (Pressed(Keys.F2, k, _prev)) _bridge.SetMode(GameplayBridge.Mode.Mario);',
  '',
  '        if (Pressed(Keys.Escape, k, _prev)) _menu = !_menu;',
  '        if (Pressed(Keys.F5, k, _prev)) _bridge.ResetToDefaults();',
  '        if (Pressed(Keys.K, k, _prev)) _bridge.ApplyDamage(1);',
  '        if (Pressed(Keys.L, k, _prev)) _bridge.Heal(1);',
  '',
  '        _bridge.Tick();',
  '        _prev = k;',
  '',
  '        var coins = _bridge.GetCoins();',
  '        var tgt = _bridge.GetCoinTarget();',
  '        var key = _bridge.Flags.GetBool("has_dream_key") ? "1" : "0";',
  '        var last = string.IsNullOrWhiteSpace(_bridge.Last) ? "-" : _bridge.Last;',
  '        var menu = _menu ? "ON" : "off";',
  '',
  '        Game.Window.Title =',
  '            "CDE KERNEL GUI v3c | MENU=" + menu +',
  '            " | mode=" + _bridge.ActiveMode +',
  '            " scene=" + _bridge.SceneId +',
  '            " pos=(" + _bridge.X.ToString("0.00") + "," + _bridge.Y.ToString("0.00") + ")" +',
  '            " HP=" + _bridge.Hp + "/" + _bridge.MaxHp +',
  '            " coins=" + coins + "/" + tgt +',
  '            " key=" + key +',
  '            " last=" + last +',
  '            " | (ESC menu, F5 reset, K dmg, L heal)";',
  '',
  '        base.Update(gameTime);',
  '    }',
  '',
  '    public override void Draw(GameTime gameTime)',
  '    {',
  '        if (_sb == null || _px == null){ base.Draw(gameTime); return; }',
  '        _sb.Begin(samplerState: SamplerState.PointClamp);',
  '',
  '        int sx = 20 + (int)(_bridge.X * 12f);',
  '        int sy = 60 + (int)(_bridge.Y * 12f);',
  '        _sb.Draw(_px, new Rectangle(sx, sy, 18, 18), Color.LimeGreen);',
  '',
  '        if (_menu)',
  '        {',
  '            _sb.Draw(_px, new Rectangle(10, 10, 260, 140), new Color(0, 0, 0, 180));',
  '            _sb.Draw(_px, new Rectangle(20, 25, 240, 25), new Color(40, 40, 40, 220));',
  '            _sb.Draw(_px, new Rectangle(20, 60, 240, 25), new Color(40, 40, 40, 220));',
  '            _sb.Draw(_px, new Rectangle(20, 95, 240, 25), new Color(40, 40, 40, 220));',
  '        }',
  '',
  '        _sb.End();',
  '        base.Draw(gameTime);',
  '    }',
  '}',
)
$overlayText = (@($overlayLines) -join "`n") + "`n"
Write-Utf8NoBomLf $OverlayPath $overlayText
Write-Host ("WROTE: " + $OverlayPath) -ForegroundColor Green

$host = ReadAllTextUtf8 $HostPath
if($host -notmatch "CDE_KERNEL_OVERLAY_V3B"){ Write-Host ("WARN: host marker not found (overlay may not be attached): " + $HostPath) -ForegroundColor Yellow }
Write-Host "NEXT: dotnet build .\CDE.sln -c Debug" -ForegroundColor Yellow
Write-Host "NEXT: dotnet run --project .\src\CDE.Game\CDE.Game.csproj -c Debug" -ForegroundColor Yellow
